services:
  fullstackdevelopment:
    image: wordpress:6.7.1
    container_name: fullstackdevelopment
    restart: always
    volumes:
      - ./db-dumps:/var/www/html/wp-content/db-dumps
      - ./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./wp-content/plugins/advanced-css-blocks:/var/www/html/wp-content/plugins/advanced-css-blocks
      - ./wp-content/plugins/are-you-paying-attention:/var/www/html/wp-content/plugins/are-you-paying-attention
      - ./wp-content/plugins/bookstore:/var/www/html/wp-content/plugins/bookstore
      - ./wp-content/plugins/bookstore-block:/var/www/html/wp-content/plugins/bookstore-block:cached
      - ./wp-content/plugins/copyright-date-block:/var/www/html/wp-content/plugins/copyright-date-block
      - ./wp-content/plugins/featured-professor:/var/www/html/wp-content/plugins/featured-professor
      - ./wp-content/plugins/interactivity-quiz:/var/www/html/wp-content/plugins/interactivity-quiz
      - ./wp-content/plugins/my-nav:/var/www/html/wp-content/plugins/my-nav
      - ./wp-content/plugins/new-database-table:/var/www/html/wp-content/plugins/new-database-table
      - ./wp-content/plugins/our-first-unique-plugin:/var/www/html/wp-content/plugins/our-first-unique-plugin
      - ./wp-content/plugins/our-word-filter-plugin:/var/www/html/wp-content/plugins/our-word-filter-plugin
      - ./wp-content/plugins/pets-custom-post-type:/var/www/html/wp-content/plugins/pets-custom-post-type
      - ./wp-content/plugins/solved-counter:/var/www/html/wp-content/plugins/solved-counter
      - ./wp-content/plugins/udemy-plus:/var/www/html/wp-content/plugins/udemy-plus
      - ./wp-content/plugins/university-post-types.php:/var/www/html/wp-content/plugins/university-post-types.php
      - ./wp-content/themes/fictional-clean-blocks:/var/www/html/wp-content/themes/fictional-clean-blocks
      - ./wp-content/themes/udemy:/var/www/html/wp-content/themes/udemy
      - ./wp-content/themes/fullstack-theme:/var/www/html/wp-content/themes/fullstack-theme
      - uploads_fullstack:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: db_fullstack
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: fullstackdevelopment
    depends_on:
      - db_fullstack
    networks:
      - wp_network
    labels:
      - "traefik.http.routers.fullstack.rule=Host(`fullstackdevelopment.local`)"
      - "traefik.http.routers.fullstack.entrypoints=web"
      - "traefik.http.routers.fullstack.service=your-service"
      - "traefik.http.routers.fullstackdevelopment.rule=HostRegexp(`^.+.fullstackdevelopment.local`)"
      - "traefik.http.routers.subdomains.entrypoints=web"
      - "traefik.http.routers.subdomains.service=your-service"
      - "traefik.http.services.your-service.loadbalancer.server.port=80"

  db_fullstack:
    image: mysql:8.0
    container_name: db_fullstack
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullstackdevelopment
    volumes:
      - db_data_fullstack:/var/lib/mysql
    networks:
      - wp_network

networks:
  wp_network:
    external: true

volumes:
  db_data_fullstack:
  uploads_fullstack: